const express = require('express')
const app = express()
const port = 3000
const mongoose = require('mongoose')
const bodyParser = require('body-parser')
const cors = require('cors')
const User = require('./models/UserDetails')
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: true }))